import { useMemo, useState } from 'react'
import { Activity, AlertCircle, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookCopy, BookOpen, Bookmark, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Download, FileBarChart2, Filter, LibraryBig, MoreHorizontal, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, TrendingUp, UserRound, Users, X } from 'lucide-react'
import { ActivityChart, Avatar, ConfirmDialog, CoverArt, DonutChart, IssueForm, Modal, RecordForm, StatusPill, TransactionTable } from '../components/LibraryShared.jsx'
import { daysLate, formatDate, hashPassword, money, normalizeEmail, today } from '../lib/helpers.js'

export function BookDetail({ book, onBack, onSaveBook, transactions, canEdit = true }) {
  const [editing, setEditing] = useState(false)
  const history = transactions.filter((item) => item.bookId === book.id).slice(0, 4)
  return <><button className="back-link" onClick={onBack}><ArrowLeft size={15} />Back to catalog</button><section className="panel detail-panel"><div className="detail-cover"><CoverArt book={book} /></div><div className="detail-content"><span className="category-label">{book.category}</span><h1>{book.title}</h1><p className="detail-author">by {book.author}</p><div className="detail-tags"><StatusPill status={book.available ? 'Available' : 'Checked out'} /><span>{book.available} available of {book.copies} copies</span></div><div className="detail-meta"><div><span>Catalog ID</span><strong>{book.id}</strong></div><div><span>ISBN</span><strong>{book.isbn || 'Not listed'}</strong></div><div><span>Published</span><strong>{book.year}</strong></div><div><span>Total checkouts</span><strong>{book.borrowed}</strong></div></div>{canEdit && <button className="button button-primary" onClick={() => setEditing(true)}><Settings size={15} />Edit book details</button>}</div></section><section className="panel history-panel"><div className="panel-heading"><div><span className="eyebrow">CIRCULATION</span><h2>Recent loan history</h2></div></div><TransactionTable transactions={history} /></section>{editing && <RecordForm kind="book" record={book} onSave={(updated) => { onSaveBook(updated); setEditing(false) }} onClose={() => setEditing(false)} />}</>
}
