import { useMemo, useState } from 'react'
import { Activity, AlertCircle, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookCopy, BookOpen, Bookmark, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Download, FileBarChart2, Filter, LibraryBig, MoreHorizontal, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, TrendingUp, UserRound, Users, X } from 'lucide-react'
import { ActivityChart, Avatar, ConfirmDialog, CoverArt, DonutChart, IssueForm, Modal, RecordForm, StatusPill, TransactionTable } from '../components/LibraryShared.jsx'
import { daysLate, formatDate, hashPassword, money, normalizeEmail, today } from '../lib/helpers.js'

export function BorrowersPage({ borrowers, setBorrowers, transactions, onToast }) {
  const [query, setQuery] = useState('')
  const [modal, setModal] = useState(false)
  const [editing, setEditing] = useState(null)
  const [deleting, setDeleting] = useState(null)
  const visible = borrowers.filter((borrower) => `${borrower.name} ${borrower.id} ${borrower.email} ${borrower.course}`.toLowerCase().includes(query.toLowerCase()))
  const save = (record) => { setBorrowers((current) => editing ? current.map((item) => item.id === editing.id ? record : item) : [record, ...current]); setModal(false); setEditing(null); onToast(editing ? 'Borrower profile updated' : 'Borrower added') }
  return <><div className="page-intro"><p>Manage member profiles and keep track of their activity.</p><button className="button button-primary" onClick={() => { setEditing(null); setModal(true) }}><Plus size={16} />Add borrower</button></div><section className="panel table-panel"><div className="toolbar"><label className="search-field"><Search size={16} /><input placeholder="Search name, student ID, or email…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><span className="table-count">{visible.length} members</span></div><div className="table-scroll"><table><thead><tr><th>Borrower</th><th>Student ID</th><th>Program</th><th>Books out</th><th>Member since</th><th>Status</th><th /></tr></thead><tbody>{visible.map((borrower) => <tr key={borrower.id}><td><div className="person-cell"><Avatar name={borrower.name} /><div><strong>{borrower.name}</strong><span>{borrower.email}</span></div></div></td><td>{borrower.id}</td><td>{borrower.course}</td><td><strong>{transactions.filter((item) => item.borrowerId === borrower.id && item.status !== 'Returned').length}</strong></td><td>{formatDate(borrower.joined)}</td><td><StatusPill status={borrower.status} /></td><td><div className="row-actions"><button className="icon-button small" aria-label={`Edit ${borrower.name}`} onClick={() => { setEditing(borrower); setModal(true) }}><Settings size={15} /></button><button className="icon-button small danger-icon" aria-label={`Delete ${borrower.name}`} onClick={() => setDeleting(borrower)}><Trash2 size={15} /></button></div></td></tr>)}{!visible.length && <tr><td colSpan="7" className="empty-cell">No borrowers found.</td></tr>}</tbody></table></div></section>{modal && <RecordForm kind="borrower" record={editing} onSave={save} onClose={() => setModal(false)} />}{deleting && <ConfirmDialog title="Delete borrower?" message={`Remove ${deleting.name} (${deleting.id}) from the borrower list? Existing transaction history will be kept.`} onClose={() => setDeleting(null)} onConfirm={() => { setBorrowers((current) => current.filter((item) => item.id !== deleting.id)); setDeleting(null); onToast('Borrower removed') }} />}</>
}
