import { useMemo, useState } from 'react'
import { Activity, AlertCircle, ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Bell, BookCopy, BookOpen, Bookmark, CalendarDays, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, Download, FileBarChart2, Filter, LibraryBig, MoreHorizontal, Plus, Search, Settings, ShieldCheck, SlidersHorizontal, Sparkles, Trash2, TrendingUp, UserRound, Users, X } from 'lucide-react'
import { ActivityChart, Avatar, ConfirmDialog, CoverArt, DonutChart, IssueForm, Modal, RecordForm, StatusPill, TransactionTable } from '../components/LibraryShared.jsx'
import { daysLate, formatDate, hashPassword, money, normalizeEmail, today } from '../lib/helpers.js'

export function ReportsPage({ books, transactions }) {
  const topBooks = [...books].sort((a, b) => b.borrowed - a.borrowed).slice(0, 6)
  const categories = [...new Set(books.map((item) => item.category))].map((name) => ({ name, count: books.filter((item) => item.category === name).length })).sort((a, b) => b.count - a.count).slice(0, 6)
  const states = ['Borrowed', 'Returned', 'Overdue'].map((name) => ({ name, count: transactions.filter((item) => item.status === name).length }))
  const max = Math.max(...topBooks.map((item) => item.borrowed), 1)
  return <><div className="page-intro"><p>A clear picture of what your readers love and what needs attention.</p><button className="button button-outline" onClick={() => window.print()}><Download size={15} />Export report</button></div><div className="report-grid"><section className="panel report-panel top-books-report"><div className="panel-heading"><div><span className="eyebrow">COLLECTION ENGAGEMENT</span><h2>Most borrowed titles</h2></div><span className="report-period">All time</span></div><div className="horizontal-bars">{topBooks.map((book) => <div className="bar-row" key={book.id}><span className="bar-name">{book.title}</span><div className="bar-track"><span style={{ width: `${(book.borrowed / max) * 100}%` }} /></div><strong>{book.borrowed}</strong></div>)}</div></section><section className="panel report-panel"><div className="panel-heading"><div><span className="eyebrow">COLLECTION MIX</span><h2>By category</h2></div></div><div className="category-breakdown">{categories.map((item, index) => <div className="category-row" key={item.name}><span className={`category-marker marker-${index}`} /><span>{item.name}</span><strong>{item.count}</strong><span className="category-percent">{Math.round((item.count / books.length) * 100)}%</span></div>)}</div></section><section className="panel report-panel distribution-report"><div className="panel-heading"><div><span className="eyebrow">CIRCULATION SNAPSHOT</span><h2>Transaction distribution</h2></div></div><div className="distribution-content"><DonutChart transactions={transactions} /><div className="distribution-note"><strong>{transactions.length}</strong><span>transactions recorded</span><small>Includes all current demo records.</small></div></div></section><section className="panel report-panel availability-report"><div className="panel-heading"><div><span className="eyebrow">INVENTORY HEALTH</span><h2>Availability by copies</h2></div></div><div className="availability-meter"><div><span>Available</span><strong>{books.reduce((sum, item) => sum + item.available, 0)} <small>copies</small></strong></div><div className="meter-track"><span style={{ width: `${Math.max(4, (books.reduce((sum, item) => sum + item.available, 0) / (books.reduce((sum, item) => sum + item.copies, 0) || 1)) * 100)}%` }} /></div><div className="meter-legend"><span><i className="legend-swatch navy" />Available</span><span><i className="legend-swatch gold" />Checked out</span></div></div></section></div><section className="panel report-table"><div className="panel-heading"><div><span className="eyebrow">TRANSACTION STATUS</span><h2>Circulation counts</h2></div></div><div className="status-report-grid">{states.map((item) => <div className="status-report-item" key={item.name}><StatusPill status={item.name} /><strong>{item.count}</strong><span>records</span></div>)}</div></section></>
}
